const actionTypes={
    FETCH_STUDENTS_START:"FETCH_STUDENT_START",
    FETCH_STUDENTS_SUCCESS:"FETCH_STUDENTS_SUCCESS",
    FETCH_STUDENTS_FAIL:"FETCH_STUDENTS_FAIL",
    ADD_STUDENT:"ADD_STUDENT",
    DELETE_STUDENT:"DELETE_STUDENT"
}





export default actionTypes;